# robot1:
#   ros__parameters:
    
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

#     io_and_status_controller:
#       type: ur_controllers/GPIOController

#     speed_scaling_state_broadcaster:
#       type: ur_controllers/SpeedScalingStateBroadcaster
#       state_publish_rate: 100.0

#     force_torque_sensor_broadcaster:
#       type: ur_controllers/ForceTorqueStateBroadcaster
#       sensor_name: tcp_fts_sensor
#       state_interface_names:
#         - force.x
#         - force.y
#         - force.z
#         - torque.x
#         - torque.y
#         - torque.z
#       frame_id: tool0
#       topic_name: ft_data

#     joint_trajectory_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#       joints:
#         - robot1/shoulder_pan_joint
#         - robot1/shoulder_lift_joint
#         - robot1/elbow_joint
#         - robot1/wrist_1_joint
#         - robot1/wrist_2_joint
#         - robot1/wrist_3_joint
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position
#         - velocity
#       state_publish_rate: 100.0
#       action_monitor_rate: 20.0
#       allow_partial_joints_goal: false
#       constraints:
#         stopped_velocity_tolerance: 0.2
#         goal_time: 0.0
#         robot1/shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/elbow_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

#     scaled_joint_trajectory_controller:
#       type: ur_controllers/ScaledJointTrajectoryController
#       joints:
#         - robot1/shoulder_pan_joint
#         - robot1/shoulder_lift_joint
#         - robot1/elbow_joint
#         - robot1/wrist_1_joint
#         - robot1/wrist_2_joint
#         - robot1/wrist_3_joint
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position
#         - velocity
#       state_publish_rate: 100.0
#       action_monitor_rate: 20.0
#       allow_partial_joints_goal: false
#       constraints:
#         stopped_velocity_tolerance: 0.2
#         goal_time: 0.0
#         robot1/shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/elbow_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
#         robot1/wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

#     forward_velocity_controller:
#       type: velocity_controllers/JointGroupVelocityController
#       joints:
#         - robot1/shoulder_pan_joint
#         - robot1/shoulder_lift_joint
#         - robot1/elbow_joint
#         - robot1/wrist_1_joint
#         - robot1/wrist_2_joint
#         - robot1/wrist_3_joint
#       interface_name: velocity

#     forward_position_controller:
#       type: position_controllers/JointGroupPositionController
#       joints:
#         - robot1/shoulder_pan_joint
#         - robot1/shoulder_lift_joint
#         - robot1/elbow_joint
#         - robot1/wrist_1_joint
#         - robot1/wrist_2_joint
#         - robot1/wrist_3_joint
controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: ur_controllers/ForceTorqueStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    scaled_joint_trajectory_controller:
      type: ur_controllers/ScaledJointTrajectoryController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController


robot1:
  joint_state_broadcaster:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster

  io_and_status_controller:
    ros__parameters:
      type: ur_controllers/GPIOController

  speed_scaling_state_broadcaster:
    ros__parameters:
      type: ur_controllers/SpeedScalingStateBroadcaster
      state_publish_rate: 100.0

  force_torque_sensor_broadcaster:
    ros__parameters:
      type: ur_controllers/ForceTorqueStateBroadcaster
      sensor_name: tcp_fts_sensor
      state_interface_names:
        - force.x
        - force.y
        - force.z
        - torque.x
        - torque.y
        - torque.z
      frame_id: tool0
      topic_name: ft_data

  joint_trajectory_controller:
    ros__parameters:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - robot1/shoulder_pan_joint
        - robot1/shoulder_lift_joint
        - robot1/elbow_joint
        - robot1/wrist_1_joint
        - robot1/wrist_2_joint
        - robot1/wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        robot1/shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/elbow_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

  scaled_joint_trajectory_controller:
    ros__parameters:
      type: ur_controllers/ScaledJointTrajectoryController
      joints:
        - robot1/shoulder_pan_joint
        - robot1/shoulder_lift_joint
        - robot1/elbow_joint
        - robot1/wrist_1_joint
        - robot1/wrist_2_joint
        - robot1/wrist_3_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: false
      constraints:
        stopped_velocity_tolerance: 0.2
        goal_time: 0.0
        robot1/shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/elbow_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
        robot1/wrist_3_joint: { trajectory: 0.2, goal: 0.1 }

  forward_velocity_controller:
    ros__parameters:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - robot1/shoulder_pan_joint
        - robot1/shoulder_lift_joint
        - robot1/elbow_joint
        - robot1/wrist_1_joint
        - robot1/wrist_2_joint
        - robot1/wrist_3_joint
      interface_name: velocity

  forward_position_controller:
    ros__parameters:
      type: position_controllers/JointGroupPositionController
      joints:
        - robot1/shoulder_pan_joint
        - robot1/shoulder_lift_joint
        - robot1/elbow_joint
        - robot1/wrist_1_joint
        - robot1/wrist_2_joint
        - robot1/wrist_3_joint
