control_params:
  lambda: [8.0, 8.0, 8.0, 2.0, 2.0, 2.0] 
  k: [50, 50, 50, 50, 50, 50]    
  k2: [0.3, 0.3, 0.3, 1, 1., 1.]
  boundary: 0.3                        
  damping_factor: 0.01                  
  waypoint_tolerance: 0.02            
  safety_limits:
    max_joint_velocity: 3.0             
  waypoints:
    - position: [0.2, 0.1, 0.5]
      orientation: [0.0, 0.0, 0.0, 1.0]